# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/oneplus5/setup-makefiles.sh
LOCAL_PATH := $(call my-dir)
ifeq ($(TARGET_DEVICE),oneplus5)
$(shell mkdir -p $(TARGET_OUT_VENDOR)/lib/egl && pushd $(TARGET_OUT_VENDOR)/lib > /dev/null && ln -sf egl/libEGL_adreno.so libEGL_adreno.so && popd > /dev/null)
$(shell mkdir -p $(TARGET_OUT_VENDOR)/lib64/egl && pushd $(TARGET_OUT_VENDOR)/lib64 > /dev/null && ln -sf egl/libEGL_adreno.so libEGL_adreno.so && popd > /dev/null)
endif
